/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.databaseproject;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author G.Q
 */
public class addStuforMng extends javax.swing.JFrame {
    public static int presetcase;
    public static String username;
    public static String ID;
    public static boolean darkmode;
    public static String projname;
    public static String desc;
    public static int ppm;
    
    static Color darkcolor =new java.awt.Color(0,153,255);
    static Color lightcolor = new java.awt.Color(56, 175, 255);
    static Color lightercolor =new java.awt.Color(66,179,255);
    static managerview1 outview;
    /**
     * Creates new form addStuforMng
     */
    public addStuforMng(String u,boolean d,String id,Color dark,Color light,Color lighter,managerview1 e) {
        username=u;
        darkmode=d;
        ID=id;
        darkcolor=dark;
        lightcolor=light;
        lightercolor= lighter;
        outview = e;
        
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        ddtext = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        mmtext = new javax.swing.JTextField();
        yytext = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dbstudent(2).png"))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Student");

        jButton1.setBackground(new java.awt.Color(56, 175, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("Birthdate:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setText("Last name:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("ID number:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("Gender:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setText("First name:");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("enter first name here");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2.setText("enter last name here");
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        ddtext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ddtext.setForeground(new java.awt.Color(153, 153, 153));
        ddtext.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ddtext.setText("DD");
        ddtext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ddtextMouseClicked(evt);
            }
        });
        ddtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddtextActionPerformed(evt);
            }
        });

        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        jTextField5.setText("enter personal ID number here");
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5MouseClicked(evt);
            }
        });
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 255));
        jLabel7.setText("E-mail address:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 255));
        jLabel8.setText("Phone number:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 255));
        jLabel9.setText("Department ID:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 255));
        jLabel10.setText("College Year:");

        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        jTextField6.setText("enter E-mail address here");
        jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField6MouseClicked(evt);
            }
        });
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextField7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        jTextField7.setText("enter phone number here");
        jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField7MouseClicked(evt);
            }
        });
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextField8.setVisible(false);
        jTextField8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(153, 153, 153));
        jTextField8.setText("enter department ID here");
        jTextField8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField8MouseClicked(evt);
            }
        });
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jTextField9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(153, 153, 153));
        jTextField9.setText("enter college year here");
        jTextField9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField9MouseClicked(evt);
            }
        });
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jCheckBox1.setText("female");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jCheckBox2.setText("male");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        mmtext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mmtext.setForeground(new java.awt.Color(153, 153, 153));
        mmtext.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        mmtext.setText("MM");
        mmtext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mmtextMouseClicked(evt);
            }
        });
        mmtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmtextActionPerformed(evt);
            }
        });

        yytext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        yytext.setForeground(new java.awt.Color(153, 153, 153));
        yytext.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        yytext.setText("YYYY");
        yytext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yytextMouseClicked(evt);
            }
        });
        yytext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yytextActionPerformed(evt);
            }
        });

        jTextField10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(153, 153, 153));
        jTextField10.setText("enter password here");
        jTextField10.setPreferredSize(new java.awt.Dimension(143, 26));
        jTextField10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField10MouseClicked(evt);
            }
        });
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jTextField11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(153, 153, 153));
        jTextField11.setText("enter username here");
        jTextField11.setPreferredSize(new java.awt.Dimension(143, 26));
        jTextField11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField11MouseClicked(evt);
            }
        });
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 255));
        jLabel11.setText("Password:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 255));
        jLabel12.setText("Username:");

        jComboBox1.setMaximumRowCount(9);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "010D", "011D", "012D", "013D", "014D" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Confirm");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jCheckBox2)
                                                .addGap(55, 55, 55)
                                                .addComponent(jCheckBox1))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                                                .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                                                .addComponent(jTextField1)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(ddtext, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(mmtext, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(yytext, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ddtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mmtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yytext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sure[]={"Yes","No"};
        var exit = JOptionPane.showOptionDialog(null,"Are you sure?", "Close student addition confirmation", 0, 1,null, sure, sure[0]);
        if(exit == 0){
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        if ("enter first name here".equals(jTextField1.getText()))
        {
            jTextField1.setText("");
            jTextField1.setForeground(Color.black);}

        if ("".equals(jTextField2.getText()))
        {
            jTextField2.setText("enter last name here");
            jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(ddtext.getText()))
        {
            ddtext.setText("DD");
            ddtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        //    if ("".equals(jTextField4.getText()))
        //  {
            //   jTextField4.setText("enter (m) for male and (f) for female");
            //    jTextField4.setForeground(new java.awt.Color(153, 153, 153));
            //}
        if ("".equals(jTextField5.getText()))
        {
            jTextField5.setText("enter personal ID number here");
            jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField6.getText()))
        {
            jTextField6.setText("enter E-mail address here");
            jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField7.getText()))
        {
            jTextField7.setText("enter phone number here");
            jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField8.getText()))
        {
            jTextField8.setText("enter department ID here");
            jTextField8.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField9.getText()))
        {
            jTextField9.setText("enter college year here");
            jTextField9.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(yytext.getText()))
        {
            yytext.setText("YYYY");
            yytext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(mmtext.getText()))
        {
            mmtext.setText("MM");
            mmtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField11.getText()))
        {
            jTextField11.setText("enter username here");
            jTextField11.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField10.getText()))
        {
            jTextField10.setText("enter password here");
            jTextField10.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        // TODO add your handling code here:
        if ("enter last name here".equals(jTextField2.getText()))
        {
            jTextField2.setText("");
            jTextField2.setForeground(Color.black);}
        if ("".equals(jTextField1.getText()))
        {
            jTextField1.setText("enter first name here");
            jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        }

        if ("".equals(ddtext.getText()))
        {
            ddtext.setText("DD");
            ddtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        //    if ("".equals(jTextField4.getText()))
        //   {
            //     jTextField4.setText("enter (m) for male and (f) for female");
            //     jTextField4.setForeground(new java.awt.Color(153, 153, 153));
            //  }
        if ("".equals(jTextField5.getText()))
        {
            jTextField5.setText("enter personal ID number here");
            jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField6.getText()))
        {
            jTextField6.setText("enter E-mail address here");
            jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField7.getText()))
        {
            jTextField7.setText("enter phone number here");
            jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField8.getText()))
        {
            jTextField8.setText("enter department ID here");
            jTextField8.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField9.getText()))
        {
            jTextField9.setText("enter college year here");
            jTextField9.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(yytext.getText()))
        {
            yytext.setText("YYYY");
            yytext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(mmtext.getText()))
        {
            mmtext.setText("MM");
            mmtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField11.getText()))
        {
            jTextField11.setText("enter username here");
            jTextField11.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField10.getText()))
        {
            jTextField10.setText("enter password here");
            jTextField10.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void ddtextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ddtextMouseClicked
        // TODO add your handling code here:
        if ("DD".equals(ddtext.getText()))
        {
            ddtext.setText("");
            ddtext.setForeground(Color.black);}
        if ("".equals(jTextField1.getText()))
        {
            jTextField1.setText("enter first name here");
            jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField2.getText()))
        {
            jTextField2.setText("enter last name here");
            jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        }

        //   if ("".equals(jTextField4.getText()))
        //  {
            //     jTextField4.setText("enter (m) for male and (f) for female");
            //    jTextField4.setForeground(new java.awt.Color(153, 153, 153));
            // }
        if ("".equals(jTextField5.getText()))
        {
            jTextField5.setText("enter personal ID number here");
            jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField6.getText()))
        {
            jTextField6.setText("enter E-mail address here");
            jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField7.getText()))
        {
            jTextField7.setText("enter phone number here");
            jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField8.getText()))
        {
            jTextField8.setText("enter department ID here");
            jTextField8.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField9.getText()))
        {
            jTextField9.setText("enter college year here");
            jTextField9.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(mmtext.getText()))
        {
            mmtext.setText("MM");
            mmtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(yytext.getText()))
        {
            yytext.setText("YYYY");
            yytext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField11.getText()))
        {
            jTextField11.setText("enter username here");
            jTextField11.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField10.getText()))
        {
            jTextField10.setText("enter password here");
            jTextField10.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_ddtextMouseClicked

    private void ddtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddtextActionPerformed

    private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
        // TODO add your handling code here:
        if ("enter personal ID number here".equals(jTextField5.getText()))
        {
            jTextField5.setText("");
            jTextField5.setForeground(Color.black);}
        if ("".equals(jTextField1.getText()))
        {
            jTextField1.setText("enter first name here");
            jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField2.getText()))
        {
            jTextField2.setText("enter last name here");
            jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(ddtext.getText()))
        {
            ddtext.setText("DD");
            ddtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        //  if ("".equals(jTextField4.getText()))
        // {
            //   jTextField4.setText("enter (m) for male and (f) for female");
            //   jTextField4.setForeground(new java.awt.Color(153, 153, 153));
            //}

        if ("".equals(jTextField6.getText()))
        {
            jTextField6.setText("enter E-mail address here");
            jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField7.getText()))
        {
            jTextField7.setText("enter phone number here");
            jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField8.getText()))
        {
            jTextField8.setText("enter department ID here");
            jTextField8.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField9.getText()))
        {
            jTextField9.setText("enter college year here");
            jTextField9.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(mmtext.getText()))
        {
            mmtext.setText("MM");
            mmtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(yytext.getText()))
        {
            yytext.setText("YYYY");
            yytext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField11.getText()))
        {
            jTextField11.setText("enter username here");
            jTextField11.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField10.getText()))
        {
            jTextField10.setText("enter password here");
            jTextField10.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField5MouseClicked

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MouseClicked
        // TODO add your handling code here:
        if ("enter E-mail address here".equals(jTextField6.getText()))
        {
            jTextField6.setText("");
            jTextField6.setForeground(Color.black);}
        if ("".equals(jTextField1.getText()))
        {
            jTextField1.setText("enter first name here");
            jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField2.getText()))
        {
            jTextField2.setText("enter last name here");
            jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(ddtext.getText()))
        {
            ddtext.setText("DD");
            ddtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        //   if ("".equals(jTextField4.getText()))
        //  {
            //    jTextField4.setText("enter (m) for male and (f) for female");
            //    jTextField4.setForeground(new java.awt.Color(153, 153, 153));
            // }
        if ("".equals(jTextField5.getText()))
        {
            jTextField5.setText("enter personal ID number here");
            jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        }

        if ("".equals(jTextField7.getText()))
        {
            jTextField7.setText("enter phone number here");
            jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField8.getText()))
        {
            jTextField8.setText("enter department ID here");
            jTextField8.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField9.getText()))
        {
            jTextField9.setText("enter college year here");
            jTextField9.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(mmtext.getText()))
        {
            mmtext.setText("MM");
            mmtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(yytext.getText()))
        {
            yytext.setText("YYYY");
            yytext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField11.getText()))
        {
            jTextField11.setText("enter username here");
            jTextField11.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField10.getText()))
        {
            jTextField10.setText("enter password here");
            jTextField10.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField6MouseClicked

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseClicked
        // TODO add your handling code here:
        if ("enter phone number here".equals(jTextField7.getText()))
        {
            jTextField7.setText("");
            jTextField7.setForeground(Color.black);}
        if ("".equals(jTextField1.getText()))
        {
            jTextField1.setText("enter first name here");
            jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField2.getText()))
        {
            jTextField2.setText("enter last name here");
            jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(ddtext.getText()))
        {
            ddtext.setText("DD");
            ddtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        //   if ("".equals(jTextField4.getText()))
        //  {
            //    jTextField4.setText("enter (m) for male and (f) for female");
            //   jTextField4.setForeground(new java.awt.Color(153, 153, 153));
            //  }
        if ("".equals(jTextField5.getText()))
        {
            jTextField5.setText("enter personal ID number here");
            jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField6.getText()))
        {
            jTextField6.setText("enter E-mail address here");
            jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField8.getText()))
        {
            jTextField8.setText("enter department ID here");
            jTextField8.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField9.getText()))
        {
            jTextField9.setText("enter college year here");
            jTextField9.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(mmtext.getText()))
        {
            mmtext.setText("MM");
            mmtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(yytext.getText()))
        {
            yytext.setText("YYYY");
            yytext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField11.getText()))
        {
            jTextField11.setText("enter username here");
            jTextField11.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField10.getText()))
        {
            jTextField10.setText("enter password here");
            jTextField10.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField7MouseClicked

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField8MouseClicked
        // TODO add your handling code here:
        if ("enter department ID here".equals(jTextField8.getText()))
        {
            jTextField8.setText("");
            jTextField8.setForeground(Color.black);}
        if ("".equals(jTextField1.getText()))
        {
            jTextField1.setText("enter first name here");
            jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField2.getText()))
        {
            jTextField2.setText("enter last name here");
            jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(ddtext.getText()))
        {
            ddtext.setText("DD");
            ddtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        //   if ("".equals(jTextField4.getText()))
        //  {
            //    jTextField4.setText("enter (m) for male and (f) for female");
            //    jTextField4.setForeground(new java.awt.Color(153, 153, 153));
            /// }
        if ("".equals(jTextField5.getText()))
        {
            jTextField5.setText("enter personal ID number here");
            jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField6.getText()))
        {
            jTextField6.setText("enter E-mail address here");
            jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField7.getText()))
        {
            jTextField7.setText("enter phone number here");
            jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField9.getText()))
        {
            jTextField9.setText("enter college year here");
            jTextField9.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(mmtext.getText()))
        {
            mmtext.setText("MM");
            mmtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(yytext.getText()))
        {
            yytext.setText("YYYY");
            yytext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField11.getText()))
        {
            jTextField11.setText("enter username here");
            jTextField11.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField10.getText()))
        {
            jTextField10.setText("enter password here");
            jTextField10.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField8MouseClicked

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField9MouseClicked
        // TODO add your handling code here:
        if ("enter college year here".equals(jTextField9.getText()))
        {
            jTextField9.setText("");
            jTextField9.setForeground(Color.black);}
        if ("".equals(jTextField1.getText()))
        {
            jTextField1.setText("enter first name here");
            jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField2.getText()))
        {
            jTextField2.setText("enter last name here");
            jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(ddtext.getText()))
        {
            ddtext.setText("DD");
            ddtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        //  if ("".equals(jTextField4.getText()))
        // {
            //   jTextField4.setText("enter (m) for male and (f) for female");
            //   jTextField4.setForeground(new java.awt.Color(153, 153, 153));
            //}
        if ("".equals(jTextField5.getText()))
        {
            jTextField5.setText("enter personal ID number here");
            jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField6.getText()))
        {
            jTextField6.setText("enter E-mail address here");
            jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField7.getText()))
        {
            jTextField7.setText("enter phone number here");
            jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField8.getText()))
        {
            jTextField8.setText("enter department ID here");
            jTextField8.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(mmtext.getText()))
        {
            mmtext.setText("MM");
            mmtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(yytext.getText()))
        {
            yytext.setText("YYYY");
            yytext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField11.getText()))
        {
            jTextField11.setText("enter username here");
            jTextField11.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField10.getText()))
        {
            jTextField10.setText("enter password here");
            jTextField10.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField9MouseClicked

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed
    char gender;
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        gender = 'F';
        jCheckBox2.setSelected(false);
        //jCheckBox2.setForeground(Color.black);
        // jCheckBox1.setForeground(new java.awt.Color(255,102,255));
        //  if (!jCheckBox1.isSelected())
        // {
            //     jCheckBox1.setForeground(Color.black);
            //  }
        if ("".equals(jTextField1.getText()))
        {
            jTextField1.setText("enter first name here");
            jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField2.getText()))
        {
            jTextField2.setText("enter last name here");
            jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(ddtext.getText()))
        {
            ddtext.setText("DD");
            ddtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        //  if ("".equals(jTextField4.getText()))
        // {
            //   jTextField4.setText("enter (m) for male and (f) for female");
            //   jTextField4.setForeground(new java.awt.Color(153, 153, 153));
            //}
        if ("".equals(jTextField5.getText()))
        {
            jTextField5.setText("enter personal ID number here");
            jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField6.getText()))
        {
            jTextField6.setText("enter E-mail address here");
            jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField7.getText()))
        {
            jTextField7.setText("enter phone number here");
            jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField8.getText()))
        {
            jTextField8.setText("enter department ID here");
            jTextField8.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField9.getText()))
        {
            jTextField9.setText("enter college year here");
            jTextField9.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(yytext.getText()))
        {
            yytext.setText("YYYY");
            yytext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(mmtext.getText()))
        {
            mmtext.setText("MM");
            mmtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField11.getText()))
        {
            jTextField11.setText("enter username here");
            jTextField11.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField10.getText()))
        {
            jTextField10.setText("enter password here");
            jTextField10.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
        gender = 'M';
        jCheckBox1.setSelected(false);
        // jCheckBox2.setForeground(Color.blue);
        //  jCheckBox1.setForeground(Color.black);
        //    if (!jCheckBox2.isSelected())
        //  {
            //     jCheckBox2.setForeground(Color.black);
            //  }
        if ("".equals(jTextField1.getText()))
        {
            jTextField1.setText("enter first name here");
            jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField2.getText()))
        {
            jTextField2.setText("enter last name here");
            jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(ddtext.getText()))
        {
            ddtext.setText("DD");
            ddtext.setForeground(new java.awt.Color(153, 153, 153));

        }
        //  if ("".equals(jTextField4.getText()))
        // {
            //   jTextField4.setText("enter (m) for male and (f) for female");
            //   jTextField4.setForeground(new java.awt.Color(153, 153, 153));
            //}
        if ("".equals(jTextField5.getText()))
        {
            jTextField5.setText("enter personal ID number here");
            jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField6.getText()))
        {
            jTextField6.setText("enter E-mail address here");
            jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField7.getText()))
        {
            jTextField7.setText("enter phone number here");
            jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField8.getText()))
        {
            jTextField8.setText("enter department ID here");
            jTextField8.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField9.getText()))
        {
            jTextField9.setText("enter college year here");
            jTextField9.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(yytext.getText()))
        {
            yytext.setText("YYYY");
            yytext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(mmtext.getText()))
        {
            mmtext.setText("MM");
            mmtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField11.getText()))
        {
            jTextField11.setText("enter username here");
            jTextField11.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField10.getText()))
        {
            jTextField10.setText("enter password here");
            jTextField10.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void mmtextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mmtextMouseClicked
        // TODO add your handling code here:
        if ("MM".equals(mmtext.getText()))
        {
            mmtext.setText("");
            mmtext.setForeground(Color.black);}
        if ("".equals(jTextField1.getText()))
        {
            jTextField1.setText("enter first name here");
            jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField2.getText()))
        {
            jTextField2.setText("enter last name here");
            jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        }

        //   if ("".equals(jTextField4.getText()))
        //  {
            //     jTextField4.setText("enter (m) for male and (f) for female");
            //    jTextField4.setForeground(new java.awt.Color(153, 153, 153));
            // }
        if ("".equals(jTextField5.getText()))
        {
            jTextField5.setText("enter personal ID number here");
            jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField6.getText()))
        {
            jTextField6.setText("enter E-mail address here");
            jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField7.getText()))
        {
            jTextField7.setText("enter phone number here");
            jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField8.getText()))
        {
            jTextField8.setText("enter department ID here");
            jTextField8.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField9.getText()))
        {
            jTextField9.setText("enter college year here");
            jTextField9.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(ddtext.getText()))
        {
            ddtext.setText("DD");
            ddtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(yytext.getText()))
        {
            yytext.setText("YYYY");
            yytext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField11.getText()))
        {
            jTextField11.setText("enter username here");
            jTextField11.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField10.getText()))
        {
            jTextField10.setText("enter password here");
            jTextField10.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_mmtextMouseClicked

    private void mmtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mmtextActionPerformed

    private void yytextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yytextMouseClicked
        // TODO add your handling code here:
        if ("YYYY".equals(yytext.getText()))
        {
            yytext.setText("");
            yytext.setForeground(Color.black);}
        if ("".equals(jTextField1.getText()))
        {
            jTextField1.setText("enter first name here");
            jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField2.getText()))
        {
            jTextField2.setText("enter last name here");
            jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        }

        //   if ("".equals(jTextField4.getText()))
        //  {
            //     jTextField4.setText("enter (m) for male and (f) for female");
            //    jTextField4.setForeground(new java.awt.Color(153, 153, 153));
            // }
        if ("".equals(jTextField5.getText()))
        {
            jTextField5.setText("enter personal ID number here");
            jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField6.getText()))
        {
            jTextField6.setText("enter E-mail address here");
            jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField7.getText()))
        {
            jTextField7.setText("enter phone number here");
            jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField8.getText()))
        {
            jTextField8.setText("enter department ID here");
            jTextField8.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField9.getText()))
        {
            jTextField9.setText("enter college year here");
            jTextField9.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(ddtext.getText()))
        {
            ddtext.setText("DD");
            ddtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(mmtext.getText()))
        {
            mmtext.setText("MM");
            mmtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField11.getText()))
        {
            jTextField11.setText("enter username here");
            jTextField11.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField10.getText()))
        {
            jTextField10.setText("enter password here");
            jTextField10.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_yytextMouseClicked

    private void yytextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yytextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yytextActionPerformed

    private void jTextField10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField10MouseClicked
        // TODO add your handling code here:
        if ("enter password here".equals(jTextField10.getText()))
        {
            jTextField10.setText("");
            jTextField10.setForeground(Color.black);}
        if ("".equals(jTextField1.getText()))
        {
            jTextField1.setText("enter first name here");
            jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField2.getText()))
        {
            jTextField2.setText("enter last name here");
            jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(ddtext.getText()))
        {
            ddtext.setText("DD");
            ddtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        //    if ("".equals(jTextField4.getText()))
        //  {
            //   jTextField4.setText("enter (m) for male and (f) for female");
            //    jTextField4.setForeground(new java.awt.Color(153, 153, 153));
            //}
        if ("".equals(jTextField5.getText()))
        {
            jTextField5.setText("enter personal ID number here");
            jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField6.getText()))
        {
            jTextField6.setText("enter E-mail address here");
            jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField7.getText()))
        {
            jTextField7.setText("enter phone number here");
            jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField8.getText()))
        {
            jTextField8.setText("enter department ID here");
            jTextField8.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField9.getText()))
        {
            jTextField9.setText("enter college year here");
            jTextField9.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(yytext.getText()))
        {
            yytext.setText("YYYY");
            yytext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(mmtext.getText()))
        {
            mmtext.setText("MM");
            mmtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField11.getText()))
        {
            jTextField11.setText("enter username here");
            jTextField11.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField10MouseClicked

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField11MouseClicked
        // TODO add your handling code here:
        if ("enter username here".equals(jTextField11.getText()))
        {
            jTextField11.setText("");
            jTextField11.setForeground(Color.black);}
        if ("".equals(jTextField1.getText()))
        {
            jTextField1.setText("enter first name here");
            jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField2.getText()))
        {
            jTextField2.setText("enter last name here");
            jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(ddtext.getText()))
        {
            ddtext.setText("DD");
            ddtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        //    if ("".equals(jTextField4.getText()))
        //  {
            //   jTextField4.setText("enter (m) for male and (f) for female");
            //    jTextField4.setForeground(new java.awt.Color(153, 153, 153));
            //}
        if ("".equals(jTextField5.getText()))
        {
            jTextField5.setText("enter personal ID number here");
            jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField6.getText()))
        {
            jTextField6.setText("enter E-mail address here");
            jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField7.getText()))
        {
            jTextField7.setText("enter phone number here");
            jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField8.getText()))
        {
            jTextField8.setText("enter department ID here");
            jTextField8.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField9.getText()))
        {
            jTextField9.setText("enter college year here");
            jTextField9.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(yytext.getText()))
        {
            yytext.setText("YYYY");
            yytext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(mmtext.getText()))
        {
            mmtext.setText("MM");
            mmtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField9.getText()))
        {
            jTextField9.setText("enter college year here");
            jTextField9.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField10.getText()))
        {
            jTextField10.setText("enter password here");
            jTextField10.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField11MouseClicked

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
        if ("".equals(jTextField1.getText()))
        {
            jTextField1.setText("enter first name here");
            jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField2.getText()))
        {
            jTextField2.setText("enter last name here");
            jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(ddtext.getText()))
        {
            ddtext.setText("DD");
            ddtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        //   if ("".equals(jTextField4.getText()))
        //  {
            //    jTextField4.setText("enter (m) for male and (f) for female");
            //    jTextField4.setForeground(new java.awt.Color(153, 153, 153));
            /// }
        if ("".equals(jTextField5.getText()))
        {
            jTextField5.setText("enter personal ID number here");
            jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField6.getText()))
        {
            jTextField6.setText("enter E-mail address here");
            jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField7.getText()))
        {
            jTextField7.setText("enter phone number here");
            jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField9.getText()))
        {
            jTextField9.setText("enter college year here");
            jTextField9.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(mmtext.getText()))
        {
            mmtext.setText("MM");
            mmtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(yytext.getText()))
        {
            yytext.setText("YYYY");
            yytext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField11.getText()))
        {
            jTextField11.setText("enter username here");
            jTextField11.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField10.getText()))
        {
            jTextField10.setText("enter password here");
            jTextField10.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if ("".equals(jTextField1.getText()))
        {
            jTextField1.setText("enter first name here");
            jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField2.getText()))
        {
            jTextField2.setText("enter last name here");
            jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(ddtext.getText()))
        {
            ddtext.setText("DD");
            ddtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        //   if ("".equals(jTextField4.getText()))
        //  {
            //    jTextField4.setText("enter (m) for male and (f) for female");
            //    jTextField4.setForeground(new java.awt.Color(153, 153, 153));
            /// }
        if ("".equals(jTextField5.getText()))
        {
            jTextField5.setText("enter personal ID number here");
            jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField6.getText()))
        {
            jTextField6.setText("enter E-mail address here");
            jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField7.getText()))
        {
            jTextField7.setText("enter phone number here");
            jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField9.getText()))
        {
            jTextField9.setText("enter college year here");
            jTextField9.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(mmtext.getText()))
        {
            mmtext.setText("MM");
            mmtext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(yytext.getText()))
        {
            yytext.setText("YYYY");
            yytext.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField11.getText()))
        {
            jTextField11.setText("enter username here");
            jTextField11.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField10.getText()))
        {
            jTextField10.setText("enter password here");
            jTextField10.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        jButton2.setBackground(new java.awt.Color(56,175,255));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
        jButton2.setBackground(new java.awt.Color(0, 153, 255));
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String[] options = { "create account", "cancel"};
        var exit = JOptionPane.showOptionDialog(null, "are you sure your account info is correct?", "exit",
            0, 1, null, options, options[0]);
        if (exit == 0) {
            //write create account code here
            try {
                // TODO add your handling code here:
                //Saving Student properties in Database:

                DriverManager.registerDriver(new org.postgresql.Driver());
                String cInfo = "jdbc:postgresql://localhost:5432/postgres";
                Connection con = DriverManager.getConnection(cInfo,"ghassanq","0123");
                con.setAutoCommit(false);

                String date = this.mmtext.getText() + "-" + this.ddtext.getText() + "-" +this.yytext.getText();

                //String EngIDs_sql = "select \"ID\" from architecture_firm.\"Full-time_Engineer\"";
                //String EngIDsCount_sql = "select count (\"ID\") from architecture_firm.\"Full-time_Engineer\"";

                //int EngIDs_count = 0;

                Statement stmt = con.createStatement();

                //ResultSet EngIDsCount_rs = stmt.executeQuery(EngIDsCount_sql);
                //while(EngIDsCount_rs.next()){
                    //    EngIDs_count = EngIDsCount_rs.getInt("count");
                    //}

                //String EngIDarr[] = new String[EngIDs_count];

                //ResultSet EngIDs_rs = stmt.executeQuery(EngIDs_sql);
                //int randIndex = 0;

                //for(int i=0;i<EngIDarr.length;i++){
                    //    if(EngIDs_rs.next()){
                        //        EngIDarr[i] = EngIDs_rs.getString("ID");
                        //    }
                    //    Random rand = new Random();
                    //    randIndex = rand.nextInt(EngIDarr.length);
                    //}

                //System.out.println(EngIDarr[randIndex]); just checking the random EngID generating.
                this.jTextField8.setText(this.jComboBox1.getSelectedItem().toString());
                String qry = "insert into architecture_firm.\"Student_trainee\" values('" + this.jTextField5.getText() + "','" + this.jTextField1.getText() + "','" + this.jTextField2.getText() + "','" + this.jTextField11.getText() + "','" + this.jTextField10.getText() + "','" + date + "','" + gender + "','" + this.jTextField7.getText() + "','" + this.jTextField6.getText() + "','" + this.jTextField8.getText() + "','" + "8am - 2pm" + "','" + this.jTextField9.getText() + "','" + 100 + "','" + ID /*"EngID"*/ +"')";

                stmt.executeUpdate(qry);

                con.commit();
                con.close();

                JOptionPane.showMessageDialog(null,"Student added successfully!");

                outview.dispose();
                dispose();
                managerview1 a = new managerview1(username,ID);
                a.showMngStus();
                a.setVisible(true);

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.toString());
            }
        }
        if (exit == 1) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addStuforMng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addStuforMng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addStuforMng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addStuforMng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addStuforMng().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ddtext;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField mmtext;
    private javax.swing.JTextField yytext;
    // End of variables declaration//GEN-END:variables
}
