/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.databaseproject;


import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 * @author Msys
 */


public class editcustomeraccount extends javax.swing.JFrame {
    
public static boolean darkmode;
public static String username;
public static String ID;
static customerview1 outview;

static Color darkcolor =new java.awt.Color(0,153,255);
static Color lightcolor = new java.awt.Color(56, 175, 255);
static Color lightercolor =new java.awt.Color(66,179,255);
    /**
     * Creates new form editcustomeraccount
     */
    public editcustomeraccount(boolean d,String u,String id,customerview1 a,Color dark,Color light,Color lighter) {
        darkmode=d;
        username=u;
        ID=id;
        outview=a;
        darkcolor =dark;
        lightcolor =light;
        lightercolor = lighter;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        if(darkmode)
        jPanel1.setBackground(new java.awt.Color(61,61,61));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setBackground(darkcolor);
        if(darkmode){
            jPanel2.setBackground(new java.awt.Color(20, 20, 20));
        }

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customerprofilepic(1)seethru.png"))); // NOI18N
        if(darkmode)
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customerprofilepic(1)dark.png"))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Customer");
        jLabel22.setText(username);

        jButton1.setBackground(new java.awt.Color(56, 175, 255));
        jButton1.setBackground(lightcolor);
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        if(darkmode)
        jButton1.setBackground(new java.awt.Color(41,41,41));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(57, 57, 57)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setForeground(darkcolor);
        if(darkmode)
        jLabel3.setForeground(Color.white);
        jLabel3.setText("Last name:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setForeground(darkcolor);
        if(darkmode)
        jLabel4.setForeground(Color.white);
        jLabel4.setText("E-mail address:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setForeground(darkcolor);
        if(darkmode)
        jLabel5.setForeground(Color.white);
        jLabel5.setText("Phone number:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setForeground(darkcolor);
        if(darkmode)
        jLabel6.setForeground(Color.white);
        jLabel6.setText("First name:");

        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("enter first name here");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2.setText("enter last name here");
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setForeground(new java.awt.Color(153, 153, 153));
        jTextField3.setVisible(false);
        jTextField3.setText("enter ID number here");
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setForeground(new java.awt.Color(153, 153, 153));
        jTextField4.setText("enter phone number here");
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        jTextField5.setText("enter E-mail address here");
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5MouseClicked(evt);
            }
        });
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 255));
        jLabel7.setForeground(darkcolor);
        if(darkmode)
        jLabel7.setForeground(Color.white);
        jLabel7.setText("Password:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 255));
        jLabel8.setForeground(darkcolor);
        if(darkmode)
        jLabel8.setForeground(Color.white);
        jLabel8.setText("Username:");

        jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        jTextField6.setText("enter password here");
        jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField6MouseClicked(evt);
            }
        });
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        jTextField7.setText("enter username here");
        jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField7MouseClicked(evt);
            }
        });
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        if(darkmode)
        jLabel9.setForeground(Color.white);
        jLabel9.setText("change your account information:");

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setBackground(darkcolor);
        if(darkmode)
        jButton2.setBackground(Color.black);
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Confirm");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField2)
                                .addComponent(jTextField5)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel9)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String[] options = { "exit", "cancel"};
    var exit = JOptionPane.showOptionDialog(null, "your information will not be saved if you exit.", "exit", 
                                                      0, 0, null, options, options[0]);
    if (exit == 0) {
     dispose();
    }
    if (exit == 1) { 
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        if ("enter first name here".equals(jTextField1.getText()))
        {
        
            jTextField1.setText("");
            jTextField1.setForeground(Color.black);}
        if ("".equals(jTextField2.getText()))
        {
            jTextField2.setText("enter last name here");
            jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField3.getText()))
        {
            jTextField3.setText("enter ID number here");
            jTextField3.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField4.getText()))
        {
            jTextField4.setText("enter phone number here");
            jTextField4.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField5.getText()))
        {
            jTextField5.setText("enter E-mail address here");
            jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField6.getText()))
        {
            jTextField6.setText("enter password here");
            jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField7.getText()))
        {
            jTextField7.setText("enter username here");
            jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        // TODO add your handling code here:
        if ("enter last name here".equals(jTextField2.getText()))
        {
            jTextField2.setText("");
            jTextField2.setForeground(Color.black);}
        if ("".equals(jTextField1.getText()))
        {
            jTextField1.setText("enter first name here");
            jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField3.getText()))
        {
            jTextField3.setText("enter ID number here");
            jTextField3.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField4.getText()))
        {
            jTextField4.setText("enter phone number here");
            jTextField4.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField5.getText()))
        {
            jTextField5.setText("enter E-mail address here");
            jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField6.getText()))
        {
            jTextField6.setText("enter password here");
            jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField7.getText()))
        {
            jTextField7.setText("enter username here");
            jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
        // TODO add your handling code here:
        if ("enter ID number here".equals(jTextField3.getText()))
        {
            jTextField3.setText("");
            jTextField3.setForeground(Color.black);}
        if ("".equals(jTextField1.getText()))
        {
            jTextField1.setText("enter first name here");
            jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField2.getText()))
        {
            jTextField2.setText("enter last name here");
            jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField4.getText()))
        {
            jTextField4.setText("enter phone number here");
            jTextField4.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField5.getText()))
        {
            jTextField5.setText("enter E-mail address here");
            jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField6.getText()))
        {
            jTextField6.setText("enter password here");
            jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField7.getText()))
        {
            jTextField7.setText("enter username here");
            jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField3MouseClicked

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        // TODO add your handling code here:
        if ("enter phone number here".equals(jTextField4.getText()))
        {
            jTextField4.setText("");
            jTextField4.setForeground(Color.black);}
        if ("".equals(jTextField1.getText()))
        {
            jTextField1.setText("enter first name here");
            jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField2.getText()))
        {
            jTextField2.setText("enter last name here");
            jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField3.getText()))
        {
            jTextField3.setText("enter ID number here");
            jTextField3.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField5.getText()))
        {
            jTextField5.setText("enter E-mail address here");
            jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField6.getText()))
        {
            jTextField6.setText("enter password here");
            jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField7.getText()))
        {
            jTextField7.setText("enter username here");
            jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField4MouseClicked

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
        // TODO add your handling code here:
        if ("enter E-mail address here".equals(jTextField5.getText()))
        {
            jTextField5.setText("");
            jTextField5.setForeground(Color.black);}
        if ("".equals(jTextField1.getText()))
        {
            jTextField1.setText("enter first name here");
            jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField2.getText()))
        {
            jTextField2.setText("enter last name here");
            jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField3.getText()))
        {
            jTextField3.setText("enter ID number here");
            jTextField3.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField4.getText()))
        {
            jTextField4.setText("enter phone number here");
            jTextField4.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField6.getText()))
        {
            jTextField6.setText("enter password here");
            jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField7.getText()))
        {
            jTextField7.setText("enter username here");
            jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField5MouseClicked

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MouseClicked
        // TODO add your handling code here:
        if ("enter password here".equals(jTextField6.getText()))
        {
            jTextField6.setText("");
            jTextField6.setForeground(Color.black);}
        if ("".equals(jTextField1.getText()))
        {
            jTextField1.setText("enter first name here");
            jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField2.getText()))
        {
            jTextField2.setText("enter last name here");
            jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField3.getText()))
        {
            jTextField3.setText("enter ID number here");
            jTextField3.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField4.getText()))
        {
            jTextField4.setText("enter phone number here");
            jTextField4.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField5.getText()))
        {
            jTextField5.setText("enter E-mail address here");
            jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField7.getText()))
        {
            jTextField7.setText("enter username here");
            jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField6MouseClicked

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseClicked
        // TODO add your handling code here:
        if ("enter username here".equals(jTextField7.getText()))
        {
            jTextField7.setText("");
            jTextField7.setForeground(Color.black);}
        if ("".equals(jTextField1.getText()))
        {
            jTextField1.setText("enter first name here");
            jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField2.getText()))
        {
            jTextField2.setText("enter last name here");
            jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField3.getText()))
        {
            jTextField3.setText("enter ID number here");
            jTextField3.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField4.getText()))
        {
            jTextField4.setText("enter phone number here");
            jTextField4.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField5.getText()))
        {
            jTextField5.setText("enter E-mail address here");
            jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField6.getText()))
        {
            jTextField6.setText("enter password here");
            jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField7MouseClicked

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        if(!darkmode)
        jButton2.setBackground(lightcolor);//new java.awt.Color(56,175,255));
        else
        jButton2.setBackground(new java.awt.Color(81,81,81));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
        if(!darkmode)
        jButton2.setBackground(darkcolor);//new java.awt.Color(0, 153, 255));
        else
        jButton2.setBackground(Color.black);
    }//GEN-LAST:event_jButton2MouseExited
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String[] options = { "save changes", "cancel"};
        var exit = JOptionPane.showOptionDialog(null, "save new account info?", "exit",
            0, 1, null, options, options[0]);
        if (exit == 0) {
            //write create account code here
            try {
            // TODO add your handling code here:
            //Updating customer properties in Database:
            
            DriverManager.registerDriver(new org.postgresql.Driver());
            String cInfo = "jdbc:postgresql://localhost:5432/postgres";
            Connection con = DriverManager.getConnection(cInfo,"ghassanq","0123");
            con.setAutoCommit(false);
            
            
            String updateUsernameSql = "update architecture_firm.\"Customer\" set \"User_name\" = '" + this.jTextField7.getText() + "' where \"ID\" = '" + ID + "'";            
            String updatePasswordSql = "update architecture_firm.\"Customer\" set \"Password\" = '" + this.jTextField6.getText() + "' where \"ID\" = '" + ID + "'"; 
            String updateFirstnameSql = "update architecture_firm.\"Customer\" set \"First_name\" = '" + this.jTextField1.getText() + "' where \"ID\" = '" + ID + "'";
            String updateLastnameSql = "update architecture_firm.\"Customer\" set \"Last_name\" = '" + this.jTextField2.getText() + "' where \"ID\" = '" + ID + "'";
            String updatePhoneSql = "update architecture_firm.\"Customer\" set \"Phone_number\" = '" + this.jTextField4.getText() + "' where \"ID\" = '" + ID + "'";
            String updateEmailSql = "update architecture_firm.\"Customer\" set \"Email_address\" = '" + this.jTextField5.getText() + "' where \"ID\" = '" + ID + "'";
            
            
            Statement stmt = con.createStatement();
            
            if(!(jTextField7.getText().equals("enter username here"))){
               stmt.executeUpdate(updateUsernameSql); 
               username = jTextField7.getText();
            }
            if(!(jTextField6.getText().equals("enter password here"))){
               stmt.executeUpdate(updatePasswordSql); 
            }
            if(!(jTextField1.getText().equals("enter first name here"))){
               stmt.executeUpdate(updateFirstnameSql); 
            }
            if(!(jTextField2.getText().equals("enter last name here"))){
               stmt.executeUpdate(updateLastnameSql); 
            }
            if(!(jTextField4.getText().equals("enter phone number here"))){
               stmt.executeUpdate(updatePhoneSql); 
            }
            if(!(jTextField5.getText().equals("enter E-mail address here"))){
               stmt.executeUpdate(updateEmailSql); 
            }            
            
            con.commit();
            con.close();
            
            JOptionPane.showMessageDialog(null,"Changes are saved");
            
            Boolean darkm1=darkmode;
            Color darkc1 =darkcolor;
            Color lightc1= lightcolor;
            Color lighterc1= lightercolor;
            
            outview.dispose();
            dispose();
            customerview1 a= new customerview1(username,ID);
            a.setVisible(true);
            
            a.changeTheme(darkm1,darkc1,lightc1,lighterc1);
            
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex.toString());
        }

         
            
        }
        if (exit == 1) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public void changetheme(boolean d,Color dark,Color light,Color lighter)
    {
        darkmode=d;
        darkcolor =dark;
        lightcolor =light;
        lightercolor = lighter;
        if(!darkmode)
        {
          jPanel2.setBackground(darkcolor);
          jButton1.setBackground(lightcolor);
          jButton2.setBackground(darkcolor);
          jLabel8.setForeground(darkcolor);
          jLabel7.setForeground(darkcolor);
          jLabel6.setForeground(darkcolor);
          jLabel5.setForeground(darkcolor);
          jLabel4.setForeground(darkcolor);
          jLabel3.setForeground(darkcolor);
          jLabel9.setForeground(Color.black);
          jPanel1.setBackground(new java.awt.Color(242,242,242));
        }  
        if(darkmode)
        {
          jPanel2.setBackground(Color.black);
          jButton2.setBackground(Color.black);
          jButton1.setBackground(new java.awt.Color(41,41,41));
          jLabel8.setForeground(Color.white);
          jLabel7.setForeground(Color.white);
          jLabel6.setForeground(Color.white);
          jLabel5.setForeground(Color.white);
          jLabel4.setForeground(Color.white);
          jLabel3.setForeground(Color.white);
          jLabel9.setForeground(Color.white);
          jPanel1.setBackground(new java.awt.Color(61,61,61));
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editcustomeraccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editcustomeraccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editcustomeraccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editcustomeraccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editcustomeraccount(darkmode,username,ID,outview,darkcolor,lightcolor,lightercolor).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
