/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.databaseproject;


import static com.mycompany.databaseproject.editcustomeraccount.ID;
import static com.mycompany.databaseproject.editcustomeraccount.darkcolor;
import static com.mycompany.databaseproject.editcustomeraccount.darkmode;
import static com.mycompany.databaseproject.editcustomeraccount.lightcolor;
import static com.mycompany.databaseproject.editcustomeraccount.lightercolor;
import static com.mycompany.databaseproject.editcustomeraccount.username;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.*;
import java.util.Random;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Msys
 */
public class projectcreator extends javax.swing.JFrame {

    /**
     * Creates new form projectcreator
     */
    public static int presetcase;
    public static String username;
    public static String ID;
    public static boolean darkmode;
    public static String projname;
    public static String desc;
    public static int ppm;
    
    static Color darkcolor =new java.awt.Color(0,153,255);
    static Color lightcolor = new java.awt.Color(56, 175, 255);
    static Color lightercolor =new java.awt.Color(66,179,255);
    static customerview1 outview;
    
    
    public projectcreator(int i,String u,boolean d,String id,Color dark,Color light,Color lighter,customerview1 c) {
        username=u;
        presetcase=i;
        darkmode=d;
        ID=id;
        darkcolor=dark;
        lightcolor=light;
        lightercolor= lighter;
        outview = c;
        switch (i){
    
            case 1 -> {projname="Apartment building";ppm=5;desc="Four apartments per floor each apartment has \nthree bedrooms, one living room, one kitchen, \ntwo bathrooms, one guest room";}
            case 2 -> {projname="Duplex";ppm=5;desc="Two houses each contains three bedrooms, three \nbathrooms, living room, guest room, dining room, \nkitchen";}
            case 3 -> {projname="Villa";ppm=15;desc="Four bedrooms, four bathroom, living room, guest house, kitchen, dining room";}
            case 4 -> {projname="Hospital";ppm=10;desc="50 inpatient beds, surgical suite, reception, \nadministration, outpatient, Emergency unit, \nlaboratory, imaging, services";}
            case 5 -> {projname="Rehabiliatation center";ppm=10;desc="Physio therapy, hydro therapy, imaging, Gym, \nreception, administration, outpatient, inpatient, \nservices";}
            case 6 -> {projname="Clinic";ppm=10;desc="Examination rooms, reception, administration, \nEmergency room, operating room, services";}
            case 7 -> {projname="Kindergarten";ppm=7;desc="6 classrooms, playhall, administration, teachers \nrooms, services";}
            case 8 -> {projname="elementary school";ppm=7;desc="12 classrooms, administration, teachers rooms, \ncomputer lab, science labs, library, multipurpose hall, services";}
            case 9 -> {projname="High school";ppm=7;desc="12 classrooms, administration, teachers rooms, \ncomputer lab, physics lab, chemistry lab, biology lab, library, multipurpose hall, services";}
            case 10 -> {projname="University department";ppm=10;desc="10 classrooms, 4 computer labs, library, \n4 workshops, administration, staff offices, \nmultipurpose hall, auditorium, services";}
            case 11 -> {projname="enter project type here"; ppm=7;}
                  }
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        if(darkmode)
        jPanel1.setBackground(new java.awt.Color(61,61,61));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setForeground(darkcolor);
        if(darkmode)
        jLabel2.setForeground(Color.white);
        jLabel2.setText("Project description:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setForeground(darkcolor);
        if(darkmode)
        jLabel3.setForeground(Color.white);
        jLabel3.setText("Project type:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setForeground(darkcolor);
        if(darkmode)
        jLabel6.setForeground(Color.white);
        jLabel6.setText("Number of floors:");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        switch(presetcase){
            case 1 -> jTextField1.setText("6");
            case 2 -> jTextField1.setText("2");
            case 3 -> jTextField1.setText("2");
            case 4 -> jTextField1.setText("7");
            case 5 -> jTextField1.setText("6");
            case 6 -> jTextField1.setText("2");
            case 7 -> jTextField1.setText("1");
            case 8 -> jTextField1.setText("3");
            case 9 -> jTextField1.setText("3");
            case 10 -> jTextField1.setText("4");
            case 11 ->{jTextField1.setForeground(new java.awt.Color(153, 153, 153));
                jTextField1.setText("enter number of floors here");
            }}
            /*
            jTextField1.setText("enter number of floors here");
            */
            jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTextField1MouseClicked(evt);
                }
            });
            jTextField1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField1ActionPerformed(evt);
                }
            });

            jToggleButton1.setBackground(new java.awt.Color(0, 153, 255));
            jToggleButton1.setBackground(darkcolor);
            if(darkmode)
            jToggleButton1.setBackground(Color.black);
            jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
            jToggleButton1.setText("Confirm");
            jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    jToggleButton1MouseEntered(evt);
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    jToggleButton1MouseExited(evt);
                }
            });
            jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jToggleButton1ActionPerformed(evt);
                }
            });

            jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
            jLabel7.setForeground(new java.awt.Color(0, 153, 255));
            jLabel7.setForeground(darkcolor);
            if(darkmode)
            jLabel7.setForeground(Color.white);
            jLabel7.setText("Project area:");

            jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
            jLabel8.setForeground(new java.awt.Color(0, 153, 255));
            jLabel8.setForeground(darkcolor);
            if(darkmode)
            jLabel8.setForeground(Color.white);
            jLabel8.setText("Project name:");

            jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            switch(presetcase){
                case 1 -> jTextField6.setText("650");
                case 2 -> jTextField6.setText("300");
                case 3 -> jTextField6.setText("250");
                case 4 -> jTextField6.setText("1500");
                case 5 -> jTextField6.setText("1000");
                case 6 -> jTextField6.setText("500");
                case 7 -> jTextField6.setText("400");
                case 8 -> jTextField6.setText("500");
                case 9 -> jTextField6.setText("600");
                case 10 -> jTextField6.setText("1000");
                case 11 ->{jTextField6.setForeground(new java.awt.Color(153, 153, 153));
                    jTextField6.setText("enter project area here (in square meters)");
                }}
                /*
                jTextField6.setText("enter project area here (in square meters)");
                */
                jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jTextField6MouseClicked(evt);
                    }
                });
                jTextField6.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jTextField6ActionPerformed(evt);
                    }
                });

                jTextField7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jTextField7.setText(username+"s "+projname);
                jTextField7.setForeground(Color.black);
                /*
                jTextField7.setForeground(new java.awt.Color(153, 153, 153));
                jTextField7.setText("enter project name here");
                */
                if(presetcase==11)
                {
                    jTextField7.setForeground(new java.awt.Color(153, 153, 153));

                    jTextField7.setText("enter project name here");
                }
                /*if(presetcase!=0)
                {
                    jTextField7.setText(username+"s "+projname);
                    jTextField7.setForeground(Color.black);
                }
                */
                jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jTextField7MouseClicked(evt);
                    }
                });
                jTextField7.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jTextField7ActionPerformed(evt);
                    }
                });

                jPanel2.setBackground(new java.awt.Color(0, 153, 255));
                jPanel2.setBackground(darkcolor);
                if(darkmode)
                jPanel2.setBackground(Color.black);

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("Project infromation");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                );
                jPanel2Layout.setVerticalGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                );

                jTextArea1.setColumns(20);
                jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jTextArea1.setForeground(new java.awt.Color(153, 153, 153));
                jTextArea1.setLineWrap(true);
                jTextArea1.setRows(5);
                jTextArea1.setText("enter project description here");
                if(presetcase!=11){
                    jTextArea1.setText(desc);
                    jTextArea1.setForeground(Color.black);
                }
                jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jTextArea1MouseClicked(evt);
                    }
                });
                jScrollPane1.setViewportView(jTextArea1);

                jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(0, 153, 255));
                jLabel4.setForeground(darkcolor);
                if(darkmode)
                jLabel4.setForeground(Color.white);
                jLabel4.setText("Estimated price:");
                jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseEntered(java.awt.event.MouseEvent evt) {
                        jLabel4MouseEntered(evt);
                    }
                    public void mouseExited(java.awt.event.MouseEvent evt) {
                        jLabel4MouseExited(evt);
                    }
                });

                jTextField3.setEditable(false);
                jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                jTextField3.setText("0$");
                jTextField3.setBorder(null);
                if(darkmode){
                    jTextField3.setBackground(new java.awt.Color(61,61,61));
                    jTextField3.setForeground(Color.white);}
                if(presetcase !=11)
                pricecalc();
                jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseEntered(java.awt.event.MouseEvent evt) {
                        jTextField3MouseEntered(evt);
                    }
                    public void mouseExited(java.awt.event.MouseEvent evt) {
                        jTextField3MouseExited(evt);
                    }
                });
                jTextField3.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jTextField3ActionPerformed(evt);
                    }
                });

                jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

                jLabel10.setText("m");
                if(darkmode)
                jLabel10.setForeground(Color.white);

                jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
                jLabel11.setText("2");
                if(darkmode)
                jLabel11.setForeground(Color.white);

                jTextField4.setEditable(false);
                jTextField4.setBackground(new java.awt.Color(255, 255, 255));
                jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jTextField4.setText("enter project type here");
                jTextField4.setText(projname);
                if(presetcase==11)
                {
                    if(!darkmode)
                    jTextField4.setBackground(new java.awt.Color(255,255,255));
                    if(darkmode)
                    jTextField4.setBackground(new java.awt.Color(242,242,242));
                    jTextField4.setEditable(true);
                    //jTextField4.setBorder(null);
                    jTextField4.setForeground(new java.awt.Color(153, 153, 153));
                }
                jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jTextField4MouseClicked(evt);
                    }
                });
                jTextField4.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jTextField4ActionPerformed(evt);
                    }
                });

                jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(242, 242, 242));
                jLabel5.setText("$ per meter square");
                jLabel5.setText(Integer.toString(ppm)+"$ per square meter");
                jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseEntered(java.awt.event.MouseEvent evt) {
                        jLabel5MouseEntered(evt);
                    }
                    public void mouseExited(java.awt.event.MouseEvent evt) {
                        jLabel5MouseExited(evt);
                    }
                });

                jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel12.setForeground(new java.awt.Color(0, 153, 255));
                jLabel12.setForeground(darkcolor);
                if(darkmode){
                    jLabel12.setForeground(Color.white);
                }
                jLabel12.setText("Land ID:");

                jTextField2.setBackground(new java.awt.Color(255, 255, 255));
                jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jTextField2.setForeground(new java.awt.Color(153, 153, 153));
                jTextField2.setText("enter land_ID here");
                jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jTextField2MouseClicked(evt);
                    }
                });
                jTextField2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jTextField2ActionPerformed(evt);
                    }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel5)))
                                .addGap(94, 94, 94)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(160, 160, 160))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel12))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField4)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                                    .addComponent(jTextField2))
                                .addGap(1, 1, 1)
                                .addComponent(jLabel10)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(85, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel7)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11)))
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(82, 82, 82))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
            }// </editor-fold>//GEN-END:initComponents

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        if ("enter number of floors here".equals(jTextField1.getText()))
        {
            jTextField1.setText("");
            jTextField1.setForeground(Color.black);}
        if ("".equals(jTextField7.getText()))
        {
            jTextField7.setText("enter project name here");
            jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField6.getText()))
        {
            jTextField6.setText("enter project area here (in square meters)");
            jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField4.getText()))
        {
            jTextField4.setText("enter project type here");
            jTextField4.setForeground(new java.awt.Color(153, 153, 153));
        }
         if ("".equals(jTextArea1.getText()))
        {
            jTextArea1.setText("enter project description here");
            jTextArea1.setForeground(new java.awt.Color(153, 153, 153));
        }
         if ("".equals(jTextField2.getText()))
        {
            jTextField2.setText("enter land_ID here");
            jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        }
        pricecalc();
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
            pricecalc();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jToggleButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseEntered
        // TODO add your handling code here:
        if(!darkmode)
        jToggleButton1.setBackground(lightcolor);
        if(darkmode)
        jToggleButton1.setBackground(new java.awt.Color(81,81,81));
    }//GEN-LAST:event_jToggleButton1MouseEntered

    private void jToggleButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseExited
        // TODO add your handling code here:
        if(!darkmode)
        jToggleButton1.setBackground(darkcolor);
        if(darkmode)
        jToggleButton1.setBackground(Color.black);
    }//GEN-LAST:event_jToggleButton1MouseExited

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:        
        
        boolean checkAddLand = outview.checkAddLandpanel();
            boolean checkAddProject = outview.checkAddPrject();
            boolean checkEdu = outview.checkEdu();
            boolean checkManageProjects = outview.checkManageProjects();
            boolean checkMed = outview.checkMed();
            boolean checkRes = outview.checkRes();
            boolean checkmanageLandspanel = outview.checkmanageLandspanel();
            
          String[] options = { "confirm", "cancel"};
    var exit = JOptionPane.showOptionDialog(null, "submit project?", "exit", 
                                                      0, 1, null, options, options[0]);
    if (exit == 0) {
     //write save changes code here
     try {
            // TODO add your handling code here:
            //Saving Project properties in Database:
            
            DriverManager.registerDriver(new org.postgresql.Driver());
            String cInfo = "jdbc:postgresql://localhost:5432/postgres";
            Connection con = DriverManager.getConnection(cInfo,"ghassanq","0123");
            con.setAutoCommit(false);
            
            Integer PIDrand = (int)(111 + Math.random() * 888);//A value between 111 and 999
            String PID = PIDrand.toString() + "P";
            
            String DepIDs_sql = "select \"Department_ID\" from architecture_firm.\"Project\"";
            String DepIDsCount_sql = "select count (\"Department_ID\") from architecture_firm.\"Project\"";
            
            String LandIDCount_sql = "select count (\"Land_ID\") from architecture_firm.\"Land\"where \"Owner_ID\"='" + ID + "'";
            String LandIDs_sql = "select \"Land_ID\" from architecture_firm.\"Land\" where \"Owner_ID\"='" + ID + "'";
            
            int DepIDs_count = 0;
            int LandIDs_count = 0;
            
            Statement stmt = con.createStatement();
            
            ResultSet LandsCount_rs = stmt.executeQuery(LandIDCount_sql);
            while(LandsCount_rs.next()){
                LandIDs_count = LandsCount_rs.getInt("count");
            }
            LandsCount_rs.close();
            
            String LandIDsArr[] = new String[LandIDs_count];
            
            ResultSet LandIDs_rs = stmt.executeQuery(LandIDs_sql);
            for(int i=0;i<LandIDsArr.length;i++){
                if(LandIDs_rs.next()){
                    LandIDsArr[i] = LandIDs_rs.getString("Land_ID");
                    }
            }            
            
            ResultSet DepIDsCount_rs = stmt.executeQuery(DepIDsCount_sql);
            while(DepIDsCount_rs.next()){
                DepIDs_count = DepIDsCount_rs.getInt("count");
            }
            DepIDsCount_rs.close();
            
            String DepIDarr[] = new String[DepIDs_count];          
            
            ResultSet DepIDs_rs = stmt.executeQuery(DepIDs_sql);
            int randIndex = 0;
            
                for(int i=0;i<DepIDarr.length;i++){
                    if(DepIDs_rs.next()){
                    DepIDarr[i] = DepIDs_rs.getString("Department_ID");
                    }
                    Random rand = new Random();
                    randIndex = rand.nextInt(DepIDarr.length);
            }
                
            int ownedLand = 0;
            
            for(int i=0;i<LandIDsArr.length;i++){
                if(this.jTextField2.getText().equals(LandIDsArr[i])){
                    ownedLand = 1;
                    break;
                }
            }
            int smallArea = 0;
            
            String qry = "insert into architecture_firm.\"Project\" values('" + PID + "','" + this.jTextField7.getText() + "','" + this.jTextField2.getText() + "','" + this.jTextField4.getText() + "'," + Integer.parseInt(this.jTextField1.getText()) + "," + Integer.parseInt(this.jTextField6.getText()) + ",'" + this.jTextArea1.getText() + "','" + DepIDarr[randIndex] + "','" + ID + "'," + 0 +")";
            String qry1 = "select \"Area\" from architecture_firm.\"Land\" where \"Land_ID\"='" + this.jTextField2.getText() + "'";
            
            ResultSet AreaCheckrs = stmt.executeQuery(qry1);
            while(AreaCheckrs.next()){
                if(Integer.parseInt(AreaCheckrs.getString("Area")) < Integer.parseInt(this.jTextField6.getText())){
                    smallArea = 1;
                    break;
                }
            }
            
            if(smallArea == 1){
                JOptionPane.showMessageDialog(null,"The land you provided has a smaller area than the project!","Area error",JOptionPane.ERROR_MESSAGE);
            }
            
            else if(ownedLand == 1){
                stmt.executeUpdate(qry);
                
                //Adding the project ID with the engineer to the Engineer_project table:
                //String addtoengprojqry = "insert into architecture_firm.\"Engineer_project\"(\"Engineer_ID\",\"Project_ID\") values("  + "," + PID + ")";
            
                JOptionPane.showMessageDialog(null,"Project added successfully!");
            }
            else{
                JOptionPane.showMessageDialog(null, "You dont own this land!");
            }
            
            con.commit();
            con.close();
            
            if(ownedLand == 1 && smallArea == 0){
                Boolean darkm1=darkmode;
            Color darkc1 =darkcolor;
            Color lightc1= lightcolor;
            Color lighterc1= lightercolor;
            
            outview.dispose();
            
            customerview1 a= new customerview1(username,ID);
            a.setVisible(true);
            
            if(ownedLand==1 && smallArea == 0){
                dispose();
            }
            
            
            if(checkEdu){
                a.showEdupanel();
            }
            else if(checkMed){
                a.showMedpanel();
            }
            else if(checkRes){
                a.showRespanel();
            }
            else if(checkAddProject){
                a.showProjectcreate();
            }
            else if(checkManageProjects){
                a.showManageLandspanel();
            }
            else if(checkmanageLandspanel){
                a.showManageLandspanel();
            }
            else if(checkAddLand){
                a.showAddLandPanel();
            }
            
            if(ownedLand == 0){
            this.setVisible(false);
            this.setVisible(true);
            }           
            
           a.changeTheme(darkm1, darkc1, lightc1, lighterc1); 
            }
            
                      
            
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex.toString());
        }
    }
    if (exit == 1) { 
    }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTextField6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MouseClicked
              if ("enter project area here (in square meters)".equals(jTextField6.getText()))
        {
            jTextField6.setText("");
            jTextField6.setForeground(Color.black);}
        if ("".equals(jTextField7.getText()))
        {
            jTextField7.setText("enter project name here");
            jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField1.getText()))
        {
            jTextField1.setText("enter number of floors here");
            jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField4.getText()))
        {
            jTextField4.setText("enter project type here");
            jTextField4.setForeground(new java.awt.Color(153, 153, 153));
        }
         if ("".equals(jTextArea1.getText()))
        {
            jTextArea1.setText("enter project description here");
            jTextArea1.setForeground(new java.awt.Color(153, 153, 153));
        }
         if ("".equals(jTextField2.getText()))
        {
            jTextField2.setText("enter land_ID here");
            jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        }
                 pricecalc();
    }//GEN-LAST:event_jTextField6MouseClicked

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here: 
        pricecalc();
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseClicked
        // TODO add your handling code here:
        if ("enter project name here".equals(jTextField7.getText()))
        {
            jTextField7.setText("");
            jTextField7.setForeground(Color.black);}
        if ("".equals(jTextField6.getText()))
        {
            jTextField6.setText("enter project area here (in square meters)");
            jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField1.getText()))
        {
            jTextField1.setText("enter number of floors here");
            jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField4.getText()))
        {
            jTextField4.setText("enter project type here");
            jTextField4.setForeground(new java.awt.Color(153, 153, 153));
        }
         if ("".equals(jTextArea1.getText()))
        {
            jTextArea1.setText("enter project description here");
            jTextArea1.setForeground(new java.awt.Color(153, 153, 153));
        }
         if ("".equals(jTextField2.getText()))
        {
            jTextField2.setText("enter land_ID here");
            jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField7MouseClicked
   private void pricecalc(){
      int area=0,floors=0;
         //  if(!jTextField6.getText().matches("\\d+")) 
          area=Integer.parseInt( jTextField6.getText());
       //    if(!jTextField1.getText().matches("\\d+")) 
          floors=Integer.parseInt( jTextField1.getText());
          int price = area * floors *ppm;
          jTextField3.setText(Integer.toString(price)+"$");
   }
    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextArea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MouseClicked
        // TODO add your handling code here:
                        if ("enter project description here".equals(jTextArea1.getText()))
        {
            jTextArea1.setText("");
            jTextArea1.setForeground(Color.black);}
        if ("".equals(jTextField6.getText()))
        {
            jTextField6.setText("enter project area here (in square meters)");
            jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField1.getText()))
        {
            jTextField1.setText("enter number of floors here");
            jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField7.getText()))
        {
            jTextField7.setText("enter project name here");
            jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        }
         if ("".equals(jTextField4.getText()))
        {
            jTextField4.setText("enter project type here");
            jTextField4.setForeground(new java.awt.Color(153, 153, 153));
        }  
         if ("".equals(jTextField2.getText()))
        {
            jTextField2.setText("enter land_ID here");
            jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextArea1MouseClicked

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        // TODO add your handling code here:
        if ("enter project type here".equals(jTextField4.getText()))
        {
            jTextField4.setText("");
            jTextField4.setForeground(Color.black);}
        if ("".equals(jTextField6.getText()))
        {
            jTextField6.setText("enter project area here (in square meters)");
            jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField1.getText()))
        {
            jTextField1.setText("enter number of floors here");
            jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField7.getText()))
        {
            jTextField7.setText("enter project name here");
            jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextArea1.getText()))
        {
            jTextArea1.setText("enter project description here");
            jTextArea1.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField2.getText()))
        {
            jTextField2.setText("enter land_ID here");
            jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField4MouseClicked

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
        pricecalc();
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
         if(darkmode)
         jLabel5.setForeground(new java.awt.Color(242,242,242));
        if(!darkmode)
         jLabel5.setForeground(Color.black); 
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jTextField3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseEntered
        // TODO add your handling code here:
       if(darkmode)
         jLabel5.setForeground(new java.awt.Color(242,242,242));
        if(!darkmode)
         jLabel5.setForeground(Color.black); 
    }//GEN-LAST:event_jTextField3MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
           if(!darkmode)
         jLabel5.setForeground(new java.awt.Color(242,242,242));
        if(darkmode)
         jLabel5.setForeground(new java.awt.Color(61,61,61));

    }//GEN-LAST:event_jLabel4MouseExited

    private void jTextField3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseExited
        // TODO add your handling code here:
                     if(!darkmode)
         jLabel5.setForeground(new java.awt.Color(242,242,242));
       if(darkmode)
         jLabel5.setForeground(new java.awt.Color(61,61,61));
    }//GEN-LAST:event_jTextField3MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
              if(darkmode)
         jLabel5.setForeground(new java.awt.Color(242,242,242));
        if(!darkmode)
         jLabel5.setForeground(Color.black); 
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
        if(!darkmode)
         jLabel5.setForeground(new java.awt.Color(242,242,242));
       if(darkmode)
        jLabel5.setForeground(new java.awt.Color(61,61,61)); 
    }//GEN-LAST:event_jLabel5MouseExited

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        if ("enter land_ID here".equals(jTextField2.getText()))
        {
            jTextField2.setText("");
            jTextField2.setForeground(Color.black);
        }
        if ("".equals(jTextField7.getText()))
        {
            jTextField7.setText("enter project name here");
            jTextField7.setForeground(new java.awt.Color(153, 153, 153));}
        if ("".equals(jTextField6.getText()))
        {
            jTextField6.setText("enter project area here (in square meters)");
            jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField1.getText()))
        {
            jTextField1.setText("enter number of floors here");
            jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        }
        if ("".equals(jTextField4.getText()))
        {
            jTextField4.setText("enter project type here");
            jTextField4.setForeground(new java.awt.Color(153, 153, 153));
        }
         if ("".equals(jTextArea1.getText()))
        {
            jTextArea1.setText("enter project description here");
            jTextArea1.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed
    public void changetheme(boolean d,Color dark,Color light,Color lighter)
    {
        darkmode=d;
        darkcolor =dark;
        lightcolor =light;
        lightercolor = lighter;
        if(!darkmode)
        {
          jTextField3.setBackground(new java.awt.Color(242,242,242));
          jTextField3.setForeground(Color.black);
          jPanel2.setBackground(darkcolor);
          jLabel8.setForeground(darkcolor);
          jLabel7.setForeground(darkcolor);
          jLabel6.setForeground(darkcolor);
          jLabel5.setForeground(new java.awt.Color(242,242,242));
          jLabel4.setForeground(darkcolor);
          jLabel3.setForeground(darkcolor);
          jLabel2.setForeground(darkcolor);
          jLabel9.setForeground(Color.black);
          jLabel12.setForeground(darkcolor);
          jToggleButton1.setBackground(darkcolor);
          jPanel1.setBackground(new java.awt.Color(242,242,242));
        }  
        if(darkmode)
        {
          jTextField3.setBackground(new java.awt.Color(61,61,61));
          jTextField3.setForeground(Color.white);
          jPanel2.setBackground(Color.black);
          jLabel8.setForeground(Color.white);
          jLabel7.setForeground(Color.white);
          jLabel6.setForeground(Color.white);
          jLabel5.setForeground(new java.awt.Color(61,61,61));
          jLabel4.setForeground(Color.white);
          jLabel3.setForeground(Color.white);
          jLabel2.setForeground(Color.white);
          jLabel9.setForeground(Color.white);
          jLabel12.setForeground(Color.white);
          jToggleButton1.setBackground(Color.black);
          jPanel1.setBackground(new java.awt.Color(61,61,61));
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
